---
- name: "Add NodeSource signing key"
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    id: "9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280"
    state: "present"

- name: "Add NodeSource PPA"
  apt_repository:
    repo: "{{ item }}"
    state: "present"
    filename: "nodesource"
  with_items:
    - "deb https://deb.nodesource.com/node_10.x bionic main"
    - "deb-src https://deb.nodesource.com/node_10.x bionic main"

- name: "Install Node"
  apt:
    name: "nodejs"
    state: "present"

- name: "Create PM2 user"
  user:
    name: "pm2"
    comment: "Node Process Manager"
    home: "/srv/pm2"
    create_home: "yes"
    system: "yes"
    state: "present"

- name: "Install PM2"
  npm:
    name: "pm2"
    global: "yes"
    state: "present"

- name: "Install PM2 systemd service"
  command: "pm2 startup systemd -u pm2 --hp /srv/pm2"
  args:
    creates: "/etc/systemd/system/multi-user.target.wants/pm2-pm2.service"

- name: "Start PM2 service"
  service:
    name: "pm2-pm2"
    state: "started"
...
